### ISSUE TITLE
[Question] `datetime.datetime` from `TimePoint`?

### ISSUE THREAD

**Issue by movermeyer** [metomi/isodatetime#196]
Hey everyone 👋,

I just found out about this project and was hoping to add `metomi/isodatetime` to [`ciso8601`'s parser benchmarks](https://github.com/closeio/ciso8601/blob/master/README.rst#benchmark).

Is there a way to get a [`datetime.datetime`](https://docs.python.org/3/library/datetime.html#datetime-objects) object from a `TimePoint` object?

(In my case, I'm trying to do an equivalency comparison with a datetime)

I took a quick look through this project's code, but was unsuccessful.

**Comment by MetRonnie** [comment]
Hi, I don't think we have a method for doing that, but there are a couple of ways of achieving it currently:

1. Converting to seconds since unix epoch

    ```python
    >>> from metomi.isodatetime.data import TimePoint
    >>> import datetime
    >>> timepoint = TimePoint(year=2010, month_of_year=3, hour_of_day=10, time_zone_hour=-3)
    >>> secs = int(timepoint.get("seconds_since_unix_epoch"))
    >>> datetime.fromtimestamp(secs)
    datetime.datetime(2010, 3, 1, 13, 0)
    ```

    Caveat: This loses time zone info (but does convert to UTC).

1. Using strftime/strptime

    ```python
    >>> dump_format = "%Y%m%dT%H%M%S%z"
    >>> tp_str = timepoint.strftime(dump_format)
    >>> datetime.strptime(tp_str, dump_format)
    datetime.datetime(2010, 3, 1, 10, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=75600)))
    ```

    (I've no idea why the time zone ends up weirdly for this example, but 75600 seconds minus 1 day does equal -3 hours)

Note: the above applies to isodateime 2.0.2 (current version). In the next version (likely to be called isodatetime 2.1.0), the `TimePoint.get()` method is going away and you will have to do `secs = timepoint.seconds_since_unix_epoch` instead. The next version will also contain a number of significant bug fixes and `TimePoint`s will no longer be mutable as they are in 2.0.2.

**Comment by movermeyer** [comment]
Thanks for the response. 👏 

I ended up writing a quick and dirty [comparison function](https://github.com/kinow/ciso8601/blob/6424be9cfe9538b7a243012d9d7cd23888e60a52/benchmarking/perform_comparison.py#L80-L91), that works well enough for my use case (the use case has very relaxed requirements).
